"""add status to bookings

Revision ID: 8665212c9ec9
Revises: d69e1c0eea1e
Create Date: 2025-06-27 11:42:14.258621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8665212c9ec9'
down_revision = 'd69e1c0eea1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
